Category.create!(name: 'tech stuff')
Category.create(name: 'amazing things')
Category.create(name: 'deep thoughts')

Post.create(title: 'First post', body: "Pug authentic tousled plaid, meh seitan Schlitz Tumblr disrupt. Disrupt art party sustainable forage. Art party skateboard authentic deep v squid cornhole. Chillwave squid Tonx Neutra Shoreditch, Carles mustache. Mlkshk yr fingerstache keytar, try-hard fashion axe Tonx lo-fi wayfarers cliche typewriter selvage kitsch. Kogi drinking vinegar Truffaut gastropub hella farm-to-table, vinyl pork belly. Photo booth retro meggings, single-origin coffee post-ironic scenester freegan wolf mlkshk church-key iPhone.
 Blog heirloom fashion axe cardigan, beard salvia bespoke. Gentrify crucifix YOLO master cleanse jean shorts. Sustainable retro tattooed food truck. IPhone chia farm-to-table, gentrify typewriter gastropub twee. Four loko whatever Schlitz Neutra, actually Blue Bottle yr hoodie. Synth next level deep v selvage, Tonx Banksy kitsch before they sold out swag cred mixtape hella. Taxidermy hella Schlitz small batch actually Austin skateboard banjo trust fund, semiotics vegan Carles iPhone Williamsburg tattooed.
 Literally fap kogi 90's. YOLO craft beer Brooklyn, pug cliche ethical asymmetrical. DIY distillery fanny pack normcore, Neutra Bushwick sriracha. Godard selfies VHS, Bushwick 8-bit fap Marfa flexitarian. Heirloom dreamcatcher seitan Kickstarter deep v health goth. Tote bag tattooed lo-fi literally, messenger bag art party umami McSweeney's drinking vinegar pickled salvia. Paleo PBR&B kale chips kogi, Marfa cray normcore fap craft beer.
 High Life DIY food truck, Tonx fashion axe scenester sartorial Kickstarter plaid tofu Tumblr bitters. Odd Future forage tilde single-origin coffee. Gastropub direct trade kogi, Cosby sweater letterpress Blue Bottle aesthetic normcore health goth Brooklyn tote bag hella 3 wolf moon bitters. Narwhal seitan lo-fi, authentic retro kitsch taxidermy pug semiotics flexitarian farm-to-table hoodie Portland PBR bicycle rights. Flexitarian Marfa scenester roof party fashion axe, sartorial VHS. Tofu skateboard asymmetrical, direct trade quinoa Truffaut fap salvia cardigan selvage narwhal. Put a bird on it lo-fi mustache, retro squid mlkshk flexitarian.", category_ids:[1])

Post.create(title: 'Second jpost', body: "Paleo Cosby sweater food truck jean shorts literally, occupy pug photo booth raw denim craft beer Blue Bottle crucifix Pitchfork. Neutra mustache hoodie Banksy, freegan slow-carb Cosby sweater tousled yr fixie. Williamsburg Neutra synth XOXO, shabby chic fingerstache pour-over craft beer. Flannel cray shabby chic bicycle rights cold-pressed, selvage Neutra brunch deep v. Aesthetic church-key quinoa, letterpress cornhole keffiyeh actually yr. Locavore umami kale chips whatever pork belly. IPhone pickled pork belly Brooklyn, Carles hella VHS raw denim Schlitz ugh pop-up.j", category_ids:[1,3])

Post.create(title: 'Third post', body: "long text here for a longer text there, here a body there a body, body text is everywhere ipsum dipsum flipsum gypsum.", category_ids:[1,2,3])

Post.create(title: 'Fourth post', body: "so much texting you wouldn't believe it, how many chars can you put in this totally amazing blog log dog wog long text here for a longer text there, here a body there a body, body text is everywhere ipsum dipsum flipsum gypsum.", category_ids:[2, 3])

